### ISSUE TITLE
Is there a *proper* way to directly access the Navigator's underlying WKWebView for injection purposes?

### ISSUE THREAD

**Issue by kerryknight** [readium/r2-navigator-swift#105]
Great project, guys!  Thanks so much for your hard work!

Quick question: since `EPUBSpreadView` is not marked as `open`, I'm not seeing a direct way to access the underlying `WKWebView` in order to inject my custom javascript and/or CSS.  My current workaround is to loop through the `Navigator` subviews to find the web view and reference it from there like below:
```
import R2Navigator

extension Navigator where Self: UIViewController {
    func injectJavascript(_ fileName: String) {
        if let webView = self.view.findSubviews(ofType: WKWebView.self).first,
            let filepath = Bundle.main.path(forResource: fileName, ofType: "js") {
            
            do {
                let js = try String(contentsOfFile: filepath)
                let script = WKUserScript(source: js, injectionTime: .atDocumentEnd, forMainFrameOnly: false)
                webView.configuration.userContentController.addUserScript(script)
            } catch {
                print("Error: Failed to load javascript: \(error)")
            }
        }
    }
    
    func js(_ function: String, completion: ((Any?, Error?) -> Void)? = nil) {
        if let webView = self.view.findSubviews(ofType: WKWebView.self).first {
            webView.evaluateJavaScript(function, completionHandler: completion)
        }
    }
}

// usage
navigator.injectJavascript("Bridge")
navigator.js("myFunction()")
```
This feels really gross, however.  Is there a proper way to access the webview for file injection purposes?  Thanks again for the great work.

**Comment by mickael-menu** [comment]
Hi Kerry,

It's a legitimate request, and we plan to add a way to inject CSS and JavaScript later.

However, I don't think we want to expose `EPUBSpreadView`, and maybe not even the web view itself. Because the implementation might change, and we want to keep these details private.

Two ways of injecting resources will probably be supported:
- Directly in the HTML Navigator API, through an `Injectable` dedicated API.
- Through a `ContentFilter` in the streamer – [see this issue](https://github.com/readium/architecture/issues/103). In this case, we'll probably provide a `HTMLInjectionContentFilter` which will inject the provided CSS/JS statically in the resources.

My guess is that the `ContentFilter` will be implemented first, but in the meantime, I think you can stick with your current workaround.

**Comment by kerryknight** [comment]
Ah, thanks so much for the follow-up, Mickaël.  What you outline is indeed exactly what I was hoping to find.  

In the meantime, one additional item I might note regarding my hacky workaround is that I was also forced to assign myself as the webview's delegate as I needed to be notified when the webview had finished loading (via `webView(_ webView: WKWebView, didFinish navigation: WKNavigation!)`) in order to be able to call some of my custom javascript as early as possible.  You're probably on top of it already, but for this reason it would be nice if any of the proposed injection solutions had either an asynchronous completion handler or a delegate callback so the callee would know when the javascript was safe for use.

Thanks again for your prompt response and great work on the project!
- Kerry

**Comment by mickael-menu** [comment]
> In the meantime, one additional item I might note regarding my hacky workaround is that I was also forced to assign myself as the webview's delegate as I needed to be notified when the webview had finished loading (via `webView(_ webView: WKWebView, didFinish navigation: WKNavigation!)`) in order to be able to call some of my custom javascript as early as possible.

I'm afraid that this might break fixed layout resources. Maybe you can try to swizzle the `didFinish` delegate method on `EPUBSpreadView` (assuming it's possible to do it with private classes)?
Otherwise, maybe evaluating your script after receiving the first `locationDidChange` event would work as well?

In any case, I think we need to broadcast an event when a particular resource is loaded.

**Comment by kerryknight** [comment]
Ah!  Very good point and you're exactly right--I definitely had missed that detrimental side effect of my original implementation.  I think I'll go with your `locationDidChange` suggestion for simplicity's sake.  Thanks for the tip!
