### ISSUE TITLE
RTL navigation is broken

### ISSUE THREAD

**Issue by mickael-menu** [readium/r2-navigator-swift#107]
Navigating through an RTL EPUB is currently broken in the Swift Navigator. I think it's caused by the changes I made a few months ago for the FXL 2-page spreads.

**Comment by aferditamuriqi** [comment]
@mickael-menu is there a fix planned for this? i am experiencing a lot of blank pages on production apps with RTL publication. and it seems rather a critical issue. Since it was working before with the Triptych view. I tried to compare your changes and see what i can fix, but as not much of the triptych view is left, it's not easy for me to see what caused this regression in feature.

**Comment by mickael-menu** [comment]
@aferditamuriqi I'll try to tackle this soon after the alpha release

**Comment by mickael-menu** [comment]
@aferditamuriqi It should be fixed in the PR https://github.com/readium/r2-navigator-swift/pull/136. Would you mind reviewing it before we merge?
