### ISSUE TITLE
Incorrect page snapping after going to an HTML ID, if the target element is too small

### ISSUE THREAD

**Issue by openm1nd** [readium/r2-navigator-swift#174]
Tested on
iOS: 14.5
Device: iPhone 8
Using 2.0 of R2
it happens on other devices as well

Most of the times (in scroll mode disabled) you get redirected one page before or one page after the link.

[Vinietu - Karl Mai FIXED Test.epub.zip](https://github.com/readium/r2-navigator-swift/files/6590313/Vinietu.-.Karl.Mai.FIXED.Test.epub.zip)

https://user-images.githubusercontent.com/58686775/120617881-cff56a00-c45a-11eb-9dfb-83f647ddee39.mov

**Comment by mickael-menu** [comment]
I had a look and this happens because the footnote elements are really small (only the `<sup>1</sup>` element), which doesn't work well with the `utils.js`'s `snapCurrentPosition()`, depending on your location in the web view when you click on the link (if you are before or after the destination).

When clicking on the link, the web view will scroll just enough to have the whole destination element into view, which looks like this:

<img width="400" alt="Screenshot 2021-06-04 at 10 30 32" src="https://user-images.githubusercontent.com/58686775/120772343-81120800-c520-11eb-8caa-ae7547ccc91d.png">

Then, Readium will call `snapCurrentPosition()` which takes the largest page visible on screen and snap it in place. Which in the screenshot above is the previous "wrong" page.

This problem is not always occurring because often HTML IDs are attached to whole divs which is much easier to snap accurately. So usually we don't have this issue when navigating from the table of contents or "non footnotes" links.

<img width="400" alt="Screenshot 2021-06-04 at 10 32 05" src="https://user-images.githubusercontent.com/58686775/120773328-891e7780-c521-11eb-8ed1-966e5ab2e328.png">

I won't have time to fix this any time soon, but that should get you started if you want to tackle this.

I'm not sure it will be easy, as `snapCurrentPosition()` is behaving as expected. Maybe we need to save the last destination element requested as a "reference point" when snapping.

**Comment by mickael-menu** [comment]
A fix has been initiated in this PR https://github.com/readium/r2-navigator-swift/pull/177 but it still needs some work, if someone wants to take over.

**Comment by mickael-menu** [comment]
I fixed it in this commit: https://github.com/readium/r2-navigator-swift/pull/186/commits/2d2c999fcba860d6e23f265d3cf938e24fd1bfad

Part of the Decorator PR because of the significant changes in the JS code introduced.
