### ISSUE TITLE
Question: Text Highlighting

### ISSUE THREAD

**Issue by emartinson** [readium/r2-navigator-swift#201]
Hi! Thank you for this immersive work! I'm trying to implement text highlighting.

**How can I highlight currently selected text?**

I want to implement Text to Speech with highlighting of current sentence (and pronouncing word).
I'd like to contribute to this project, but still having difficulties with understanding the basics.

**Comment by mickael-menu** [comment]
To draw highlights (or any other kind of decorations) on a page, you can use the [Decorator API](https://github.com/readium/architecture/blob/proposal/decorator-api/proposals/000-decorator-api.md), which is available in Readium 2.1.

As for interacting with the text selection, take a look at the [`SelectableNavigator`](https://github.com/readium/r2-navigator-swift/blob/develop/r2-navigator-swift/SelectableNavigator.swift) interface, which `EPUBNavigatorViewController` implements.

**Comment by emartinson** [comment]
Thank you very much!

**Comment by emartinson** [comment]
@mickael-menu I've read all these documents and now came to implementation, but seems to miss something.

I'm I right that in order me to handle text selection and text decoration I had to implement my own version of `EPUBNavigatorViewController ` as navigator?

Env:
R2 v2.1.0
Xcode 12
iOS 13+
Swift 5

**Comment by emartinson** [comment]
What do you think if we make some F.A.Q. ?
For entry level contributors for example?
I'm experienced in iOS, but new to WKWebView and JS bridging. And has difficulties with understanding why do I need cssSelector property, some JS injections, etc. If we could answer souch questions on a dedicated section may be will reduce amount of issues.

**Comment by mickael-menu** [comment]
@emartinson Do you still need help with this? It looks like you figured it out https://github.com/readium/r2-navigator-swift/issues/203#issuecomment-922840655.

Yes we're still lacking a lot documentation-wise in the project, this is something I want to fix after moving everything to a monorepo so that it's easier to maintain.

For injection, it's not yet fully supported by the toolkit, we will eventually add an "injectable" API to inject CSS, JavaScript and fonts in the publication. You have a limited way of injecting scripts by overriding [`EPUBNavigatorDelegate.navigator(_:setupUserScripts:)`](https://github.com/readium/r2-navigator-swift/blob/160b7207e0d4a08fd1d7aca65c5a0aa931d56e39/r2-navigator-swift/EPUB/EPUBNavigatorViewController.swift#L17).

> As I'm working on Text to speech - I saw you have this on your To-Do, may be I can work together with someone to contribute to Radium.

Yes I'll be personally working on this for Q4 2020, we can join forces. You might want to visit us on our Slack channels to discuss this: https://readium-slack.herokuapp.com/
