### ISSUE TITLE
Issue with long unbreakable lines

### ISSUE THREAD

**Issue by llemeurfr** [readium/r2-navigator-swift#52]
Test on the IDPF EPUB 3.0 spec publication, quite visible in scroll mode. 
There is a large table in the first resource (EPUB Publications 3.0) section 5 (Publication Resources) and the formatting breaks there. 
Result, swiping to the next resource is inefficient (a large "margin" appears before we can move to the next resource).

Same kind of issue with epub31.epub, on the first resource (EPUB Content Documents 3.1), there is a long unbreakable URL in section 3.4, which also adds a "margin" in scroll mode and provokes a superposition of text in paginated mode.

Not sure we can solve that. It may be that such HTML is non compliant with EPUB "reflowable" practices. But it may be an issue if we want to display less constrained "Web Publications".

**Comment by JayPanoz** [comment]
Hmmmm, long URLs should be safeguarded via 

https://github.com/readium/readium-css/blob/4b189e8ae65285d982e6470b0d1dc98a68665baf/css/src/modules/ReadiumCSS-safeguards.css#L37-L40

Even in scroll mode (despite the desc at the top of the stylesheet). 

Large tables… everything I can do in CSS is more or less band-aid on a wooden leg as, if we even want to force overflow, we need to put the table in another element like a `div` (or maybe a custom element to prevent CSS issues) first – but we consequently end up altering the DOM.

**Comment by HadrienGardeur** [comment]
@JayPanoz is this something that we can address entirely in Readium CSS or do we need to handle such special cases in each navigator?

**Comment by JayPanoz** [comment]
I honestly can’t remember if I checked the files with issues to see whether it’s due to an author style so I’ll re-check. 

What I would say right now is that we could probably have 3 categories:

1. breaking urls and headings is something we, the RS, want to address – and should be in Readium CSS – then it’s about deciding if we want to override in any case;
2. tables are that everlasting issue everybody requires be addressed, but nobody wants to research/discuss but Readium CSS can’t do much there w/o altering the DOM, not even an overflow;
3. breaking long words in text e.g. German, it’s up to authors because we can’t realistically address that without side issues, but Readium CSS should at least try to clip so that it doesn’t overflow on the next screen.

**Comment by mickael-menu** [comment]
Looks like there's nothing we can do directly in the Swift project.

Further discussion regarding table handling can take place here: https://github.com/readium/r2-testapp-swift/discussions/367
