### ISSUE TITLE
Button (and any other interactive form elements) should be included in list of interactive elements

### ISSUE THREAD

**Issue by sumahadevan** [readium/r2-navigator-swift#55]
The latest list of interactive tags in the file

https://github.com/readium/r2-navigator-swift/blob/develop/r2-navigator-swift/EPUB/Resources/gestures.js

does not include the tag 'button'. As a result, buttons within the EPUB do not respond immediately to touches, unless they are defined using the 'input' tag. This was verified in the latest build of R2 Reader on iOS, namely:

Version and Device Details:
R2 Reader iOS App version: 2.0.0
Build version: 21
iOS mobile device: iPod Touch 6th Generation running iOS 12.3.1.

Clearly, 'button' should be in the list of interactive tags. It appears all other interactive elements in forms are already included (they have one of the tags already on the list). A helpful reference in this regard s

https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/The_native_form_widgets

This issue was originally logged for the published app referenced below:

https://github.com/readium/r2-testapp-swift/issues/239

**Comment by mmenu-mantano** [comment]
Thanks, I will add `button` to https://github.com/readium/r2-navigator-swift/pull/51. I double-checked with your `button-click-epub3.epub` test book and it seems to fix the issue.

**Comment by mmenu-mantano** [comment]
I'm also removing
```js
event.stopPropagation();
event.preventDefault();
```
from the touch handling, as this is the reason the `button` got broken in the first place, and it doesn't bring anything useful for taps. In my opinion, we should only determine whether or not the tap should be reported to the host app, not prevent default behavior in the web view.

**Comment by JayPanoz** [comment]
@mmenu-mantano Note r2-glue-js is using the examples from the touch handling sample here: https://github.com/JayPanoz/architecture/tree/touch-handling/misc/touch-handling

It’s one of those samples that would be added in a samples repo if we had one for implementers but is kinda hidden right now because we don’t. 

At first sight, gestures.js is missing a bunch of elements: 

- `audio`
- `canvas`
- `details`
- `el contenteditable=""` (so that’s an attribute, it can be like any element) 
- anything with `preventDefault()` in authors’ script (so `defaultPrevented` – [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Event/defaultPrevented))

**Comment by mmenu-mantano** [comment]
I'm re-opening this issue to address the problems reported by Jiminy in the previous comment.

**Comment by mickael-menu** [comment]
@JayPanoz I went through your test EPUB (which is great by the way!) and fixed the missing elements for the touch handling.

I had an issue with the `defaultPrevented` case, because the EPUB was listening to the `click` event while we were handling `touchend`. In this case the events are unrelated, and we couldn't see that the click was supposed to be prevented.

I replaced `touchend` by `click` in Readium, which worked great with iOS 13, but for previous versions I had to set the CSS `cursor` property of `body` to `pointer`. Otherwise the `WKWebView` didn't emit the `click` event. (More info on that: https://www.quirksmode.org/blog/archives/2010/10/click_event_del_1.html)
